services:
  ruby:
    image: ruby:${RUBY_IMAGE:-2.7}-bullseye
    environment:
      - HISTFILE=/app/tmp/.bash_history
      - BUNDLE_PATH=/bundle
      - BUNDLE_CONFIG=/app/.bundle/config
      - REDIS_URL=redis://redis:6379/0
    command: bash
    working_dir: /app
    volumes:
      - .:/app:cached
      - bundler_data:/bundle
    tmpfs:
      - /tmp
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7
    healthcheck:
      test: redis-cli ping
      interval: 10s

volumes:
  bundler_data:
