#!/usr/bin/ruby
# frozen_string_literal: true

require "bundler/setup"
require "schked/cli"

# rubocop:disable Lint/RescueException
begin
  Schked::CLI.start(ARGV)
rescue Exception => e
  warn "Schked exited with error"
  warn(e.message) if e.respond_to?(:message)
  warn(e.backtrace.join("\n")) if e.respond_to?(:backtrace) && e.backtrace.respond_to?(:join)
  exit 1
end
# rubocop:enable Lint/RescueException
