#!/usr/bun/ruby
# frozen_string_literal: true

require "bundler/setup"
require "schked/cli"

begin
  Schked::CLI.start(ARGV)
rescue Exception => e
  $stderr.puts "Schked exited with error"
  $stderr.puts(e.message) if e.respond_to?(:message)
  $stderr.puts(e.backtrace.join("\n")) if e.respond_to?(:backtrace) && e.backtrace.respond_to?(:join)
  exit 1
end
